OK_FORMAT = True

test = {   'name': 'q2',
    'points': 3,
    'suites': [   {   'cases': [   {   'code': '>>> type(total_profit_int) == int and total_profit_int == 19980\nTrue',
                                       'failure_message': 'total_profit_int is either the incorrect value or it is not an int',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 1,
                                       'success_message': 'Good job! total_profit_int is an int and the expected value'},
                                   {   'code': '>>> type(pizza_profit_int) == int and pizza_profit_int == 555\nTrue',
                                       'failure_message': 'pizza_profit_int is either the incorrect value or it is not an int',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 1,
                                       'success_message': 'Good job! pizza_profit_int is an int and the expected value'},
                                   {   'code': '>>> type(float_profit_int) == int and float_profit_int == 222\nTrue',
                                       'failure_message': 'float_profit_int is either the incorrect value or it is not an int',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 1,
                                       'success_message': 'Good job! float_profit_int is an int and the expected value'}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
