OK_FORMAT = True

test = {   'name': 'q1',
    'points': 3,
    'suites': [   {   'cases': [   {   'code': ">>> valid_guess('1')\nFalse",
                                       'failure_message': 'Expecting string with length less than 5 to return False but it did not',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 1,
                                       'success_message': 'Good job!'},
                                   {   'code': ">>> valid_guess('123456')\nFalse",
                                       'failure_message': 'Expecting string with length more than 5 to return False but it did not',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 1,
                                       'success_message': 'Good job!'},
                                   {   'code': ">>> valid_guess('guess')\nTrue",
                                       'failure_message': 'Expecting string with length 5 to return True but it did not',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 1,
                                       'success_message': 'Good job!'}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
